# Trusty comes with AArch64 toolchain
dist: trusty

# use container-based infrastructure
sudo: false

language: c

# cross toolchain to AArch64
env:
  - CROSS_COMPILE="aarch64-linux-gnu-"

os:
  - linux
compiler:
  - gcc

# Install the toolchain
addons:
  apt:
    packages:
    - gcc-aarch64-linux-gnu

before_install:

# build (and test) using the Makefile, with a single overall status
script:
  - make PLAT=sun50iw1p1 DEBUG=1 bl31
  - make PLAT=sun50iw1p1 bl31

